BulbPower.Web/Controllers/ExperimentController.cs
using BulbPower.Business.Service.IService;
using Microsoft.AspNetCore.Mvc;

namespace BulbPower.Web.Controllers
{
    public class ExperimentController : Controller
    {
        private readonly IExperimentService _experimentService;

        public ExperimentController(IExperimentService experimentService)
        {
            _experimentService = experimentService;
        }

        public IActionResult Details(int id)
        {
            var experimentVm = _experimentService.GetExperimentVM(id);
            if (experimentVm == null)
            {
                return NotFound();
            }

            return View(experimentVm);
        }

        public IActionResult SendNextPerson(int id)
        {
            _experimentService.SendNextPerson(id);
            return RedirectToAction("Details", new { id });
        }

        public IActionResult ResetExperiment(int id)
        {
            _experimentService.ResetExperiment(id);
            return RedirectToAction("Details", new { id });
        }
    }
}

BulbPower.Web/Controllers/HomeController.cs
using BulbPower.Business.Service.IService;
using Microsoft.AspNetCore.Mvc;

namespace BulbPower.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IExperimentService _experimentService;

        public HomeController(IExperimentService experimentService)
        {
            _experimentService = experimentService;
        }

        public IActionResult Index()
        {
            var existingExperiments = _experimentService.ShowAllExperimentVMs();
            return View(existingExperiments);
        }

        [HttpPost]
        public IActionResult CreateExperiment(int numberOfPeople, int numberOfBulbs)
        {
            if (ModelState.IsValid)
            {
                _experimentService.CreateExperiment(numberOfPeople, numberOfBulbs);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult DeleteExperiment(int id)
        {
            _experimentService.DeleteExperiment(id);
            return RedirectToAction("Index");
        }

    }
}

BulbPower.Web/Views/Experiment/Details.cshtml
@model ExperimentVM

@{
    ViewData["Title"] = "Experiment Details";
}
<br />
<div class="col-3 col-md-2">
    <a asp-controller="Home" asp-action="Index" class="btn btn-outline-secondary border form-control" >Back to Experiment</a>
</div>
<br />
<br />
<div>
    <h3> @Model.Experiment.ExperimentName</h3>
    <br />
    <span>
        Status: @Model.Experiment.ExperimentStatus
        <form style="display:inline" asp-action="ResetExperiment" method="post">
            <input type="hidden" name="id" value="@Model.Experiment.ExperimentId" />
            <button style="padding-inline:10px; border-radius:5px" type="submit">Reset Experiment</button>
        </form>
        &nbsp;&nbsp;&nbsp;&nbsp;
        @Model.Experiment.NumberOfBulbs bulbs &nbsp;&nbsp;
        @Model.Experiment.NumberOfPeople people &nbsp;&nbsp;
        Last Exited Person Number: @Model.Experiment.LastExitedPersonNumber
        &nbsp;&nbsp;
        <form style="display:inline" asp-action="SendNextPerson" method="post">
            <input type="hidden" name="id" value="@Model.Experiment.ExperimentId" />
            <button style="padding-inline:10px; border-radius:5px" type="submit">Send Next Person</button>
        </form>
        
    </span>
</div>

<div class="row">
    @foreach (var bulb in Model.ExperimentBulbStateList)
    {
        <div class="col-md-1">
            <div class="text-center">
            @if (bulb.BulbState)
            {
                    <img src="~/images/BulbState/Bulb_On.png" width="50px" height="50px" />
            }
            else
            {
                    <img src="~/images/BulbState/Bulb_Off.png" width="50px" height="50px" />
            }
            <div>@bulb.BulbNumber</div>
            </div>
        </div>
    }
</div>

BulbPower.Web/Views/Home/Index.cshtml
@model IEnumerable<ExperimentVM>

@{
    ViewData["Title"] = "Project Bulb";
}
<br>
<br>
<br>
<div>
    <h3>Create New Experiment</h3>
    <form asp-action="CreateExperiment" method="post" >
        <input type="number" name="numberOfPeople" placeholder="Number of People" class="rounded" required>
        <span asp-validation-for="@Model.FirstOrDefault().Experiment.NumberOfPeople" class="text-danger"></span>
        &nbsp;&nbsp;
        <input type="number" name="numberOfBulbs" placeholder="Number of Bulbs" class="rounded" required>
        <span asp-validation-for="@Model.FirstOrDefault().Experiment.NumberOfBulbs" class="text-danger"></span>
        &nbsp;&nbsp;
        <button type="submit" style="padding-inline:30px; border-radius:5px">Create</button>
    </form>
</div>

<br>
<br>
<br>
@if(@Model.Count() != 0)
{
<div>
    <h3>Existing Experiments</h3>
    <table class="table table-bordered table-striped" style="width:auto">
        <thead class="" style="background-color:lightgrey">
            <tr>
                <th>Experiment Name</th>
                <th>Number of Bulbs</th>
                <th>Number of People</th>
                <th>Status</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var experiment in Model)
            {
                <tr>
                    <td>@experiment.Experiment.ExperimentName</td>
                    <td>@experiment.Experiment.NumberOfBulbs</td>
                    <td>@experiment.Experiment.NumberOfPeople</td>
                    <td>
                        @experiment.Experiment.ExperimentStatus
                        <a class="btn btn-outline-dark mx-xl-3" style="padding-inline:30px; border-radius:5px" asp-controller="Experiment" asp-action="Details" asp-route-id="@experiment.Experiment.ExperimentId">Details</a>
                        <form asp-controller="Home" asp-action="DeleteExperiment" asp-route-id="@experiment.Experiment.ExperimentId" method="post" onsubmit="return confirm('Are you sure you want to delete this experiment?');" class="d-inline">
                            <button class="btn btn-outline-danger" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    </div>
}
else
{
    <div class="alert-warning">
        <b>No Experiment exists, Create New Experiments!!</b>
    </div>
}

BulbPower.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulbPower.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulbPower.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>